theme = "catppuccin_macchiato"

[editor]
# line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.insert]
j = { k = "normal_mode" }

# Save on...
"esc" = ["normal_mode", ":w"]



[keys.normal]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
x = "extend_line"
"q" = ["move_prev_word_start", "move_next_word_end", "search_selection"]
# C-h = ["yank-diagnostic"]

# Save on...
"esc" = ["collapse_selection", ":w"]

[keys.select]
";" = ["collapse_selection", "normal_mode"]

# Same behaviour as normal mode x
x = "extend_line"

# Counterpart for normal mode V
V = "extend_to_line_end"

# Save on
"esc" = ["collapse_selection", "normal_mode", ":w"]

